### ISSUE TITLE
Error in function dynamic_proj_covariates

### ISSUE THREAD

**Issue by vineetkrdubey** [r-a-dobson/dynamicSDM#10]
I am getting an error while running this code, while all the raster files are in the local. directory   : 
save_projection_covariates<-paste0(workingdirectory,"/projection_covariates")
dynamic_proj_covariates(dates = projection_dates,
                        varnames = variablenames,
                        local.directory = projectionrasters,
                        #user.email = user.email,
                        spatial.ext = sample_extent_data,
                        spatial.res.degrees = 0.05,
                        spatial.mask = sample_extent_data,
                        resample.method = resamplemethods,
                        cov.file.type = "csv",
                        prj="+proj=longlat +datum=WGS84",
                        save.directory = save_projection_covariates
)
Error: [rast] filename is empty. Provide a valid filename

**Comment by vineetkrdubey** [comment]
Fix this thank you

**Comment by r-a-dobson** [comment]
Hi there! Thank you for getting in touch. The package maintainer is currently away in the field for the next 2 weeks. If you are able to send a sample of reproducible code that leads to this error to eerdo@leeds.ac.uk then this will help speed up the process upon their return.
