### ISSUE TITLE
potential bug in function spatiotemp_check

### ISSUE THREAD

**Issue by GretaBocedi** [r-a-dobson/dynamicSDM#11]
Hello,

we are trying to run the package for multiple species at the same time and, in cleaning the occurrence data, we came across a potential error in the function spatiotemp_check.

The argument coordclean.species has to be either of length 1 or a character vector the length of nrow(occ.data). The problem is that occ.data is already partially cleaned before the clean_coordinates is called. Hence, if we give a list of species names that is the same length of the initial occ.data, this will trigger this error:
     if (!length(coordclean.species) == 1 && !length(coordclean.species) == 
            nrow(occ.data)) {
            stop("Argument coordclean.species must be of length (1) or equal to nrow (occ.data)")
        }
Are we missing something here?

Thanks! Greta

**Comment by r-a-dobson** [comment]
Hi Greta,

Thank you for getting in touch with this bug in the package! I have now updated the spatiotemp_check() function to fix this. 

The update will take a couple of days to be uploaded on CRAN, so for an immediate fix in the meantime, please update the dynamicSDM package through:

devtools::install_github("r-a-dobson/dynamicSDM") 

I have checked that it works on one of my multi-species occurrence datasets, but please let me know if you still have a problem with the function.

Best wishes,
Rachel

**Comment by GretaBocedi** [comment]
Thank you very much, Rachel!

It works now.

All the best,
Greta

Dr Greta Bocedi (she, her)
Royal Society University Research Fellow
Co-leader, GEO BON EcoCode<https://geobon.org/ecocode-modelling-life-on-earth/>
Co-PI, EcoGenetics<https://bio.au.dk/forskning/forskningscentre/centre-for-ecological-genetics/>
School of Biological Science, University of Aberdeen
Zoology Building, Tillydrone Avenue, AB24 2TZ
Tel: +44 (0)1224 272392

Website: www.gretabocedi.com<http://www.gretabocedi.com/>
Software: RangeShifter & RangeShiftR<https://rangeshifter.github.io/>
