### ISSUE TITLE
potential bug in the spatiotemp_thin function when temporal.method = "DOY"

### ISSUE THREAD

**Issue by fernandabiologia** [r-a-dobson/dynamicSDM#13]
Hi,

I'm preparing occurrence data for a species I'm interested in the anual cycle. I'm testing the package for the first time and first I ran the spatiotemp_thin function with the temporal method = "day" which runs fine. But when I tried the method "DOY" the function gets stuck running for days and never finishes. 

I thought that maybe it was because of my large dataset (n = 21403 occurrences), so I subsetted the dataset and tested with 100 occurrences and it ran, then I kept adding 100 records, but when it gets to above 400 records sometimes the function runs somethimes it gets stuck. With 1000 records it always gets stuck, which means I can't run at all with my full dataset. I did some debugging  and it seems to get stuck in this loop: while (any(matrix)) { - on line 227 of your code. 

Any help would be much appreciated.

**Comment by r-a-dobson** [comment]
Hi there,

Thank you for getting in touch. I hope that we can get this sorted for you. Would you be able to send me a small segment of reproducible code for this error you are experiencing via email at eerdo@leeds.ac.uk.

Best wishes,
Rachel

**Comment by fernandabiologia** [comment]
Hi Rachel,

Thanks for the quick reply. I've created a test repo on github where I added the code with the parameters I'm using and a sub-sample of my dataset. I sent a collaborator invite to your email. 

Just to clarify I don't get an error message, but the function never finishes to run, I even submitted a job to a high performance computer using only 2000 records, it ran for 48h and it never finished. 

Thank you,

Fernanda.

**Comment by r-a-dobson** [comment]
Hi Fernanda,

Thank you for sending this across. I understand the problem! I will take a look at it today and get back to you with a solution. 

Best wishes,
Rachel

**Comment by r-a-dobson** [comment]
Hi Fernanda,

Thank you again for sending through the code and data earlier. I agree that the function did not necessarily have a bug but it was taking far too long when given a high number of records. Apologies for this!

I have updated the function to run much quicker with high numbers of occurrences and added in a line that reports how many were removed by temporal thinning. This update has now been sent through to GitHub, which you can install via devtools::install_github("r-a-dobson/dynamicSDM") for now. It will soon be submitted to CRAN but this will take a few days.

Please get in touch again if you still have issues with the function or any others whilst using the package. 

Best wishes,
Rachel

**Comment by fernandabiologia** [comment]
Hi Rachel,

Thank you so much for looking at this so quickly! I really appreciate it and I'm super exited to test the package for the first time.

All the best,

Fernanda.
