### ISSUE TITLE
error in the function brt_fit

### ISSUE THREAD

**Issue by fernandabiologia** [r-a-dobson/dynamicSDM#15]
Hi,

I'm following the dynamicSDM: Model fitting and autocorrelation tutorial to test the package prior running it with my own dataset which is much larger.

When I get to the step to fit the model using brt_fit() I get this error message:

_"Error in gbm.fit(x = x, y = y, offset = offset, distribution = distribution,  : 
  Bernoulli requires the response to be numeric in {0,1}"_ 

I'm simply following the tutorial and I haven't made any changes. I double checked whether the reponse variable column was numeric and only contained 0s and 1s. Everything looks fine, so I'm not sure what is happening. 

Thanks,

Fernanda.

**Comment by r-a-dobson** [comment]
Hi Fernanda

This was an expected change as the gbm package has recently updated. The latest upload of dynamicSDM to CRAN should have rectified this bug. Could you please confirm that the latest version of dynamicSDM (1.3.4) is installed?

Best wishes
Rachel

On 3 Jul 2024, at 07:45, fernandabiologia ***@***.***> wrote:

﻿

CAUTION: External Message. Use caution opening links and attachments.

Hi,

I'm following the dynamicSDM: Model fitting and autocorrelation tutorial to test the package prior running it with my own dataset which is much larger.

When I get to the step to fit the model using brt_fit() I get this error message:

"Error in gbm.fit(x = x, y = y, offset = offset, distribution = distribution, :
Bernoulli requires the response to be numeric in {0,1}"

I'm simply following the tutorial and I haven't made any changes. I double checked whether the reponse variable column was numeric and only contained 0s and 1s. Everything looks fine, so I'm not sure what is happening.

Thanks,

Fernanda.

**Comment by fernandabiologia** [comment]
Hi Rachel,

Yes, that was the issue, I was using the github version because that's where you fixed the issue with the spatial thinning. I installed the CRAN version after seeing your message and it did run the model. So, great to know that you added all the changes to the github  version :).

Thank you very much,

Fernanda.
