### ISSUE TITLE
404 Site not found

### ISSUE THREAD

**Issue by simonrolph** [r-a-dobson/dynamicSDM#3]
I tried to follow the link on the github repository: https://r-a-dobson.github.io/dynamicSDM/ but I got site not found:

![image](https://user-images.githubusercontent.com/17750766/229460189-b23ea401-02e6-42bf-8f0e-2ec887ecb6e2.png)

**Comment by r-a-dobson** [comment]
Hi Simon - I have now fixed this. Thank you for pointing this out. Rachel
